config/routes.rb
Rails.application.routes.draw do
  resources :screen_infos
  resources :condition_names
  resources :opt10075s
  resources :realtime_offered_and_bids
  resources :realtime_best_offered_and_bids
  resources :realtime_contracts
  resources :realtime_prices
  resources :balances
  resources :ordereds
  resources :orders
  resources :opt10001s
  resources :opt10080s
  resources :opt10014s
  resources :opt10059_two_twos
  resources :opt10059_two_ones
  resources :opt10059_one_twos
  resources :opt10059_one_ones
  resources :domains
  resources :themes
  get 'account/balance'

  root 'welcome#index'
  get 'welcome/index'
  get 'welcome/left'

  get 'opt10015s/where'
  get 'opt10015s/list'

  get 'opt10081s/where'
  get 'opt10081s/list'
  get 'opt10059s/where'
  get 'opt10059s/list'

  wash_out :receive

  resources :markets, only: [:show,:index,:new,:create]
  resources :stocks, only: [:show,:index,:new,:create]

  resources :branch_code_names, only: [:show,:index,:new,:create]
  resources :opt10015s, only: [:index]
  resources :opt10059s, only: [:index]
  resources :opt10081s, only: [:index]
  resources :opw00003s, only: [:show,:index,:new,:create]
  resources :opt10085s, only: [:show,:index,:new,:create]

end

app/models/balance.rb
class Balance < ActiveRecord::Base
end

app/models/domain.rb
class Domain < ActiveRecord::Base
end

app/models/market.rb
class Market < ActiveRecord::Base
	self.primary_key = 'market_code'
        has_many :market_stocks ,:foreign_key => :market_code_id
        has_many :stocks , through: :market_stocks 
end

app/models/opt10001.rb
class Opt10001 < ActiveRecord::Base
end

app/models/opt10014.rb
class Opt10014 < ActiveRecord::Base
    self.primary_key = :stock_date , :stock_code

end

app/models/opt10015.rb
class Opt10015 < ActiveRecord::Base
    self.primary_key = :stock_date , :stock_code

end

app/models/opt10059.rb
class Opt10059 < ActiveRecord::Base
    self.primary_key = :stock_date , :stock_code
end

app/models/opt10075.rb
class Opt10075 < ActiveRecord::Base
  self.primary_key = :contract_time, :order_number
end

app/models/opt10080.rb
class Opt10080 < ActiveRecord::Base
  self.primary_key = :contract_time , :stock_code
end

app/models/opt10081.rb
class Opt10081 < ActiveRecord::Base
    self.primary_key = :stock_date , :stock_code

    validates_uniqueness_of :stock_code , :scope=>"stock_date"

end

app/models/opt10085.rb
class Opt10085 < ActiveRecord::Base
  self.primary_key = :date_of_purchase , :account_number , :stock_code
end

app/models/opw00003.rb
class Opw00003 < ActiveRecord::Base
  self.primary_key = :search_date , :account_number
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/ordered.rb
class Ordered < ActiveRecord::Base
end

app/models/qpw00004.rb
class Qpw00004 < ActiveRecord::Base
end

app/models/screen_info.rb
class ScreenInfo < ActiveRecord::Base
end

app/models/stock.rb
class Stock < ActiveRecord::Base
   self.primary_keys = :stock_code
   has_many:market_stocks 
   has_many:markets,  through: :market_stocks

   has_many:theme_stocks;
   has_many:themes, through: :theme_stocks
end

app/models/theme.rb
class Theme < ActiveRecord::Base
     self.primary_keys =:theme_code
     has_many :theme_stocks, :foreign_key => :theme_code_id
     has_many :stocks, through: :theme_stocks
end

app/models/theme_stock.rb
class ThemeStock < ActiveRecord::Base
     belongs_to :stock, :foreign_key=> "stock_code_id", :primary_key =>"stock_code"
     belongs_to :theme, :foreign_key=> "theme_code_id", :primary_key =>"theme_code"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
	#원래 자동으로 이렇게 간다.
        #그리고 사실 이함수가 없어도 알아서 뷰를 찾아감.
        #그런데 내가 이걸 넣어주는이유는 상당엔 들어가는 디폴트 레이아웃을 빼는 방법을
        #알고 싶기 때문이다.
	render "welcome/index",:layout=>false
  end
end

app/helpers/jijs_helper.rb
module JijsHelper

  	$stocks=Stock.all
		$h = {}
	  $stocks.each do |stock|
		    $h[stock.stock_code] ||= []
		    $h[stock.stock_code].push(stock.stock_name)
		end

	def dateBeautifyBySecond(t)
		cute_date=Array.new
		tables=[ ["day", 24*60*60], ["hour", 60*60], ["minute", 60], ["sec", 1], ["mis", 0.001] ]
		tables.each do |unit, value|
		    o = t.divmod(value)
		    p_unit = o[0] > 1 ? unit.pluralize : unit
		    cute_date.push("#{o[0]} #{unit}") unless o[0] == 0
		    t = o[1]
		end
		return cute_date.join(', ')
	end

  def nwd(value)
		ret=number_with_delimiter(value)
    return ret
  end


  def get_stock_name(stock_code)
   #puts stock_code
	 ret = $h[stock_code.to_s]
   if(ret==nil)
     ret='못찾겠음'
   else
     ret = ret[0]
   end
    return ret
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<frameset cols="200,*" frameborder="1"> 
	<frame src="<%=welcome_left_path%>"> 
	<frame src="about:blank" name="main">
</frameset> 

app/views/welcome/left.html.erb
<ol>
        <li><%=link_to '마켓보기',markets_path, :target=>"main" %></li>
        <li><%=link_to '종목보기',stocks_path, :target=>"main" %></li>
        <li><%=link_to '계좌 금액확인',account_balance_path, :target=>"main" %></li>
        <li><%=link_to '테마그룹',themes_path , :target=>"main" %></li>
        <li><%=link_to '일일종목데이터(OPT10081)',opt10081s_path, :target=>"main" %></li>
        <li><%=link_to '회원사코드',branch_code_names_path, :target=>"main" %></li>
        <li><%=link_to '컬럼 도메인',domains_path, :target=>"main" %></li>
        <li><%=link_to "공매도추이요청<br />(OPT10014)".html_safe, opt10014s_path, :target=>"main" %></li>
        <li><%=link_to "일별거래상세요청<br />(OPT10015)".html_safe, opt10015s_path, :target=>"main" %></li>
        <li><%=link_to "종목투자자기관별_매수_금액<br />(OPT10059_one_one)".html_safe, opt10059_one_ones_path, :target=>"main" %></li>
        <li><%=link_to "종목투자자기관별_매수_수량<br />(OPT10059_one_two)".html_safe, opt10059_one_twos_path, :target=>"main" %></li>
        <li><%=link_to "종목투자자기관별_매도_금액<br />(OPT10059_two_one)".html_safe, opt10059_two_ones_path, :target=>"main" %></li>
        <li><%=link_to "종목투자자기관별_매도_수량<br />(OPT10059_two_two)".html_safe, opt10059_two_twos_path, :target=>"main" %></li>
        <li><%=link_to "종목투자자기관별<br />(OPT10059)".html_safe, opt10059s_path, :target=>"main" %></li>
        <li><%=link_to "실시간미체결요청<br />(OPT10075)".html_safe, opt10075s_path, :target=>"main" %></li>
        <li><%=link_to "1분봉<br />(OPT10081)".html_safe, opt10081s_path, :target=>"main" %></li>
        <li><%=link_to "계좌수익률요청<br />(OPT10085)".html_safe, opt10085s_path, :target=>"main" %></li>
        <li><%=link_to "추정자산조회요청<br />(OPW00003)".html_safe, opw00003s_path, :target=>"main" %></li>
        <li><%=link_to "실시간체결<br />(realtime_contract)".html_safe, realtime_contracts_path, :target=>"main" %></li>
        <li><%=link_to "실시간시세<br />(realtime_price)".html_safe, realtime_prices_path, :target=>"main" %></li>
        <li><%=link_to "주식우선호가<br />(realtime_best_offered_and_bid)".html_safe, realtime_best_offered_and_bids_path, :target=>"main" %></li>
        <li><%=link_to "주식호가잔량<br />(realtime_offered_and_bid)".html_safe, realtime_offered_and_bids_path, :target=>"main" %></li>
        <li><%=link_to "주문접수<br />(order)".html_safe, orders_path, :target=>"main" %></li>
        <li><%=link_to "주문체결<br />(ordered)".html_safe, ordereds_path, :target=>"main" %></li>
        <li><%=link_to "잔고<br />(balance)".html_safe, balances_path, :target=>"main" %></li>
        <li><%=link_to "조건검색리스트<br />(condition_name)".html_safe, condition_names_path, :target=>"main" %></li>
</ol>