config/routes.rb
Rails.application.routes.draw do
  resources :screen_infos
  resources :condition_names
  resources :opt10075s
  resources :realtime_offered_and_bids
  resources :realtime_best_offered_and_bids
  resources :realtime_contracts
  resources :realtime_prices
  resources :balances
  resources :ordereds
  resources :orders
  resources :opt10001s
  resources :opt10080s
  resources :opt10014s
  resources :opt10059_two_twos
  resources :opt10059_two_ones
  resources :opt10059_one_twos
  resources :opt10059_one_ones
  resources :domains
  resources :themes
  get 'account/balance'

  root 'welcome#index'
  get 'welcome/index'
  get 'welcome/left'

  get 'opt10015s/where'
  get 'opt10015s/list'

  get 'opt10081s/where'
  get 'opt10081s/list'
  get 'opt10059s/where'
  get 'opt10059s/list'

  wash_out :receive

  resources :markets, only: [:show,:index,:new,:create]
  resources :stocks, only: [:show,:index,:new,:create]

  resources :branch_code_names, only: [:show,:index,:new,:create]
  resources :opt10015s, only: [:index]
  resources :opt10059s, only: [:index]
  resources :opt10081s, only: [:index]
  resources :opw00003s, only: [:show,:index,:new,:create]
  resources :opt10085s, only: [:show,:index,:new,:create]

end

app/models/balance.rb
class Balance < ActiveRecord::Base
end

app/models/domain.rb
class Domain < ActiveRecord::Base
end

app/models/market.rb
class Market < ActiveRecord::Base
	self.primary_key = 'market_code'
        has_many :market_stocks ,:foreign_key => :market_code_id
        has_many :stocks , through: :market_stocks 
end

app/models/market_stock.rb
class MarketStock < ActiveRecord::Base
#       self.primary_keys = :market_code_id
	belongs_to :stock ,  :foreign_key=> "stock_code_id", :primary_key => "stock_code"
        belongs_to :market , :foreign_key=> "market_code_id", :primary_key => "market_code"
end

app/models/opt10001.rb
class Opt10001 < ActiveRecord::Base
end

app/models/opt10014.rb
class Opt10014 < ActiveRecord::Base
    self.primary_key = :stock_date , :stock_code

end

app/models/opt10015.rb
class Opt10015 < ActiveRecord::Base
    self.primary_key = :stock_date , :stock_code

end

app/models/opt10059.rb
class Opt10059 < ActiveRecord::Base
    self.primary_key = :stock_date , :stock_code
end

app/models/opt10075.rb
class Opt10075 < ActiveRecord::Base
  self.primary_key = :contract_time, :order_number
end

app/models/opt10080.rb
class Opt10080 < ActiveRecord::Base
  self.primary_key = :contract_time , :stock_code
end

app/models/opt10081.rb
class Opt10081 < ActiveRecord::Base
    self.primary_key = :stock_date , :stock_code

    validates_uniqueness_of :stock_code , :scope=>"stock_date"

end

app/models/opt10085.rb
class Opt10085 < ActiveRecord::Base
  self.primary_key = :date_of_purchase , :account_number , :stock_code
end

app/models/opw00003.rb
class Opw00003 < ActiveRecord::Base
  self.primary_key = :search_date , :account_number
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/ordered.rb
class Ordered < ActiveRecord::Base
end

app/models/qpw00004.rb
class Qpw00004 < ActiveRecord::Base
end

app/models/screen_info.rb
class ScreenInfo < ActiveRecord::Base
end

app/models/stock.rb
class Stock < ActiveRecord::Base
   self.primary_keys = :stock_code
   has_many:market_stocks 
   has_many:markets,  through: :market_stocks

   has_many:theme_stocks;
   has_many:themes, through: :theme_stocks
end

app/models/theme.rb
class Theme < ActiveRecord::Base
     self.primary_keys =:theme_code
     has_many :theme_stocks, :foreign_key => :theme_code_id
     has_many :stocks, through: :theme_stocks
end

app/models/theme_stock.rb
class ThemeStock < ActiveRecord::Base
     belongs_to :stock, :foreign_key=> "stock_code_id", :primary_key =>"stock_code"
     belongs_to :theme, :foreign_key=> "theme_code_id", :primary_key =>"theme_code"
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_params
      params.require(:domain).permit(:name, :description, :english_keyword)
    end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/jijs_helper.rb
module JijsHelper

  	$stocks=Stock.all
		$h = {}
	  $stocks.each do |stock|
		    $h[stock.stock_code] ||= []
		    $h[stock.stock_code].push(stock.stock_name)
		end

	def dateBeautifyBySecond(t)
		cute_date=Array.new
		tables=[ ["day", 24*60*60], ["hour", 60*60], ["minute", 60], ["sec", 1], ["mis", 0.001] ]
		tables.each do |unit, value|
		    o = t.divmod(value)
		    p_unit = o[0] > 1 ? unit.pluralize : unit
		    cute_date.push("#{o[0]} #{unit}") unless o[0] == 0
		    t = o[1]
		end
		return cute_date.join(', ')
	end

  def nwd(value)
		ret=number_with_delimiter(value)
    return ret
  end


  def get_stock_name(stock_code)
   #puts stock_code
	 ret = $h[stock_code.to_s]
   if(ret==nil)
     ret='못찾겠음'
   else
     ret = ret[0]
   end
    return ret
  end

end

app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :english_keyword %><br>
    <%= f.text_field :english_keyword %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form' %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Domains</h1>

<%= link_to 'New Domain', new_domain_path %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>English keyword</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @domains.each do |domain| %>
      <tr class="<%= cycle('active', 'success') %>">
        <td><%= domain.name %></td>
        <td><%= domain.description %></td>
        <td><%= domain.english_keyword %></td>
        <td><%= link_to 'Show', domain %></td>
        <td><%= link_to 'Edit', edit_domain_path(domain) %></td>
        <td><%= link_to 'Destroy', domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/domains/new.html.erb
<h1>New Domain</h1>

<%= render 'form' %>

<%= link_to 'Back', domains_path %>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @domain.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @domain.description %>
</p>

<p>
  <strong>English keyword:</strong>
  <%= @domain.english_keyword %>
</p>

<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>